/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */



package hgpi;
import java.sql.*;

public class changeTopic extends java.awt.Frame {

    /** Creates new form changeTopic */
    public changeTopic() {
        initComponents();
         try{
           Class.forName("com.mysql.jdbc.Driver");
        }
        catch(Exception e)
        {
           e.printStackTrace();
        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        label10 = new java.awt.Label();
        txbid = new java.awt.TextField();
        listctp = new java.awt.List();
        change = new java.awt.Button();
        button3 = new java.awt.Button();
        label11 = new java.awt.Label();
        txct = new java.awt.TextField();
        listctp1 = new java.awt.List();
        label12 = new java.awt.Label();
        label13 = new java.awt.Label();
        fmissing = new java.awt.Label();
        fmissing1 = new java.awt.Label();
        button2 = new java.awt.Button();
        label14 = new java.awt.Label();
        label15 = new java.awt.Label();
        label16 = new java.awt.Label();
        label17 = new java.awt.Label();
        label18 = new java.awt.Label();
        label19 = new java.awt.Label();
        label20 = new java.awt.Label();
        label21 = new java.awt.Label();
        label22 = new java.awt.Label();
        label23 = new java.awt.Label();

        setBackground(java.awt.Color.orange);
        setUndecorated(true);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(null);

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setBackground(java.awt.Color.red);
        label1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        label1.setForeground(java.awt.Color.white);
        label1.setText("CHANGE TOPIC"); // NOI18N
        add(label1);
        label1.setBounds(0, 10, 710, 60);

        label10.setAlignment(java.awt.Label.CENTER);
        label10.setBackground(java.awt.Color.blue);
        label10.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        label10.setForeground(java.awt.Color.white);
        label10.setText("BATCH ID"); // NOI18N
        add(label10);
        label10.setBounds(120, 150, 170, 30);

        txbid.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        txbid.setForeground(java.awt.Color.red);
        add(txbid);
        txbid.setBounds(440, 150, 170, 30);

        listctp.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        listctp.setForeground(java.awt.Color.red);
        add(listctp);
        listctp.setBounds(200, 500, 350, 80);

        change.setBackground(java.awt.Color.red);
        change.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        change.setForeground(java.awt.Color.blue);
        change.setLabel("CHANGE TOPIC"); // NOI18N
        change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeActionPerformed(evt);
            }
        });
        add(change);
        change.setBounds(410, 410, 170, 29);

        button3.setBackground(java.awt.Color.red);
        button3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        button3.setForeground(java.awt.Color.blue);
        button3.setLabel("SEARCH"); // NOI18N
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        add(button3);
        button3.setBounds(310, 180, 100, 29);

        label11.setAlignment(java.awt.Label.CENTER);
        label11.setBackground(java.awt.Color.blue);
        label11.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        label11.setForeground(java.awt.Color.white);
        label11.setText("2) CURRENT TOPIC"); // NOI18N
        add(label11);
        label11.setBounds(550, 310, 210, 25);

        txct.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        txct.setForeground(java.awt.Color.red);
        add(txct);
        txct.setBounds(400, 360, 170, 30);

        listctp1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        add(listctp1);
        listctp1.setBounds(200, 260, 350, 80);

        label12.setAlignment(java.awt.Label.CENTER);
        label12.setBackground(java.awt.Color.blue);
        label12.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        label12.setForeground(java.awt.Color.white);
        label12.setText("CHANGED TOPIC"); // NOI18N
        add(label12);
        label12.setBounds(200, 470, 350, 30);

        label13.setAlignment(java.awt.Label.CENTER);
        label13.setBackground(java.awt.Color.blue);
        label13.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        label13.setForeground(java.awt.Color.white);
        label13.setText("NEW TOPIC"); // NOI18N
        add(label13);
        label13.setBounds(80, 360, 170, 30);

        fmissing.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        fmissing.setForeground(java.awt.Color.white);
        fmissing.setText("Some fields are missing, please fill them!");
        fmissing.setVisible(false);
        add(fmissing);
        fmissing.setBounds(40, 420, 300, 25);

        fmissing1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        fmissing1.setForeground(java.awt.Color.white);
        fmissing1.setText("Some fields are missing, please fill them!");
        fmissing1.setVisible(false);
        add(fmissing1);
        fmissing1.setBounds(210, 100, 300, 25);

        button2.setBackground(java.awt.Color.red);
        button2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        button2.setForeground(java.awt.Color.blue);
        button2.setLabel("OK");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        add(button2);
        button2.setBounds(310, 600, 120, 29);

        label14.setAlignment(java.awt.Label.CENTER);
        label14.setBackground(java.awt.Color.blue);
        label14.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        label14.setForeground(java.awt.Color.white);
        label14.setText("SEARCH RESULT"); // NOI18N
        add(label14);
        label14.setBounds(200, 230, 350, 30);

        label15.setAlignment(java.awt.Label.CENTER);
        label15.setBackground(java.awt.Color.blue);
        label15.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        label15.setForeground(java.awt.Color.white);
        label15.setText("COURSE RESULT INDEX"); // NOI18N
        add(label15);
        label15.setBounds(550, 250, 210, 25);

        label16.setAlignment(java.awt.Label.CENTER);
        label16.setBackground(java.awt.Color.blue);
        label16.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        label16.setForeground(java.awt.Color.white);
        label16.setText("1) COURSE NAME"); // NOI18N
        add(label16);
        label16.setBounds(550, 270, 210, 25);

        label17.setAlignment(java.awt.Label.CENTER);
        label17.setBackground(java.awt.Color.blue);
        label17.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        label17.setForeground(java.awt.Color.white);
        label17.setText("1) COURSE NAME"); // NOI18N
        add(label17);
        label17.setBounds(550, 270, 210, 25);

        label18.setAlignment(java.awt.Label.CENTER);
        label18.setBackground(java.awt.Color.blue);
        label18.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        label18.setForeground(java.awt.Color.white);
        label18.setText("2) BATCH ID"); // NOI18N
        add(label18);
        label18.setBounds(550, 290, 210, 25);

        label19.setAlignment(java.awt.Label.CENTER);
        label19.setBackground(java.awt.Color.blue);
        label19.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        label19.setForeground(java.awt.Color.white);
        label19.setText("2) CHANGED TOPIC"); // NOI18N
        add(label19);
        label19.setBounds(550, 550, 210, 25);

        label20.setAlignment(java.awt.Label.CENTER);
        label20.setBackground(java.awt.Color.blue);
        label20.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        label20.setForeground(java.awt.Color.white);
        label20.setText("CHANGED TOPIC INDEX"); // NOI18N
        add(label20);
        label20.setBounds(550, 490, 210, 25);

        label21.setAlignment(java.awt.Label.CENTER);
        label21.setBackground(java.awt.Color.blue);
        label21.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        label21.setForeground(java.awt.Color.white);
        label21.setText("1) COURSE NAME"); // NOI18N
        add(label21);
        label21.setBounds(550, 510, 210, 25);

        label22.setAlignment(java.awt.Label.CENTER);
        label22.setBackground(java.awt.Color.blue);
        label22.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        label22.setForeground(java.awt.Color.white);
        label22.setText("1) COURSE NAME"); // NOI18N
        add(label22);
        label22.setBounds(550, 510, 210, 25);

        label23.setAlignment(java.awt.Label.CENTER);
        label23.setBackground(java.awt.Color.blue);
        label23.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        label23.setForeground(java.awt.Color.white);
        label23.setText("2) BATCH ID"); // NOI18N
        add(label23);
        label23.setBounds(550, 530, 210, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        //System.exit(0);
        this.dispose();
    }//GEN-LAST:event_exitForm

    private void changeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeActionPerformed
        // TODO add your handling code here:
if((txct.getText()).equals(""))
{
    fmissing1.setVisible(true);
}
else{
    fmissing.setVisible(false);
        try{
          Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/hgpi_batches?zeroDateTimeBehavior=convertToNull","root","");
            PreparedStatement p=c.prepareStatement("update batches set ctopic=? where bid=?");
            p.setString(1,txct.getText());
            p.setInt(2,Integer.parseInt(txbid.getText()));
           p.executeUpdate();
         }
         catch(Exception e)
         {
             e.printStackTrace();
         }
     try{
          Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/hgpi_batches?zeroDateTimeBehavior=convertToNull","root","");
            PreparedStatement p=c.prepareStatement("select rtrim(crsname),rtrim(bid),rtrim(ctopic) from courses c,batches b where c.crsid=b.crsid and bid=?");
             p.setInt(1,Integer.parseInt(txbid.getText()));
            ResultSet rs=p.executeQuery();
            while(rs.next())
            {
                listctp.add(rs.getString(1)+"       "+rs.getInt(2)+"        "+rs.getString(3));
            }
         }
         catch(Exception e)
         {
             e.printStackTrace();
         }
}
}//GEN-LAST:event_changeActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        // TODO add your handling code here:
        listctp1.removeAll();
        if((txbid.getText()).equals(""))
        {
            fmissing.setVisible(true);
        }
        else
        {
            fmissing.setVisible(false);
         try{
          Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/hgpi_batches?zeroDateTimeBehavior=convertToNull","root","");
            PreparedStatement p=c.prepareStatement("select rtrim(crsname),rtrim(bid),rtrim(ctopic) from courses c,batches b where c.crsid=b.crsid and bid=?");
             p.setInt(1,Integer.parseInt(txbid.getText()));
            ResultSet rs=p.executeQuery();
            while(rs.next())
            {
                listctp1.add(rs.getString(1)+"       "+rs.getInt(2)+"        "+rs.getString(3));
            }
         }
         catch(Exception e)
         {
             e.printStackTrace();
         }
        }
    }//GEN-LAST:event_button3ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
}//GEN-LAST:event_button2ActionPerformed

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_formWindowLostFocus

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new changeTopic().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button2;
    private java.awt.Button button3;
    private java.awt.Button change;
    private java.awt.Label fmissing;
    private java.awt.Label fmissing1;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label12;
    private java.awt.Label label13;
    private java.awt.Label label14;
    private java.awt.Label label15;
    private java.awt.Label label16;
    private java.awt.Label label17;
    private java.awt.Label label18;
    private java.awt.Label label19;
    private java.awt.Label label20;
    private java.awt.Label label21;
    private java.awt.Label label22;
    private java.awt.Label label23;
    private java.awt.List listctp;
    private java.awt.List listctp1;
    private java.awt.TextField txbid;
    private java.awt.TextField txct;
    // End of variables declaration//GEN-END:variables

}
