package hgpi;



import java.sql.*;




public class Frame1 extends java.awt.Frame {

    /** Creates new form Frame1 */
    static String utype;
    public Frame1(String uty) {
        super("HGPI BATCH MANAGEMENT SYSTEM");
        initComponents();
        utype=uty;
        if(utype.equals("staff"))
        {
            menu1.setEnabled(false);
            menuItem7.setEnabled(false);
            menuItem8.setEnabled(false);
            menu5.setEnabled(false);
            menu3.setEnabled(false);
        }
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/hgpi_batches?zeroDateTimeBehavior=convertToNull","root","");
            PreparedStatement ps=c.prepareStatement("select rtrim(b.bid),rtrim(bname),rtrim(crsname),rtrim(fname),rtrim(starttime),rtrim(meridian),rtrim(endtime),rtrim(meridian_to),rtrim(ctopic) from batches b,courses c,faculty f where b.crsid=c.crsid and b.facid=f.fid ORDER BY bid");
            ResultSet rs=ps.executeQuery();
            while(rs.next())
            {
                blist.add(rs.getInt(1)+"        "+rs.getString(2)+"        "+rs.getString(3)+"        "+rs.getString(4)+"        "+rs.getInt(5)+"        "+rs.getString(6)+"       "+rs.getInt(7)+"        "+rs.getString(8)+"         "+rs.getString(9));
            }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        blist = new java.awt.List();
        label1 = new java.awt.Label();
        Logout = new java.awt.Button();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        label8 = new java.awt.Label();
        label9 = new java.awt.Label();
        label10 = new java.awt.Label();
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menuItem3 = new java.awt.MenuItem();
        menuItem4 = new java.awt.MenuItem();
        menu2 = new java.awt.Menu();
        menuItem1 = new java.awt.MenuItem();
        menuItem2 = new java.awt.MenuItem();
        menu4 = new java.awt.Menu();
        menuItem7 = new java.awt.MenuItem();
        menuItem8 = new java.awt.MenuItem();
        menuItem9 = new java.awt.MenuItem();
        menu5 = new java.awt.Menu();
        menuItem5 = new java.awt.MenuItem();
        menu3 = new java.awt.Menu();
        menuItem6 = new java.awt.MenuItem();

        setBackground(new java.awt.Color(240, 240, 240));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(null);

        blist.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        blist.setForeground(java.awt.Color.red);
        blist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blistActionPerformed(evt);
            }
        });
        add(blist);
        blist.setBounds(10, 100, 350, 490);

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setBackground(java.awt.Color.red);
        label1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        label1.setForeground(java.awt.Color.white);
        label1.setText("6) MERIDIAN (AM/PM)"); // NOI18N
        add(label1);
        label1.setBounds(10, 710, 350, 20);

        Logout.setBackground(java.awt.Color.red);
        Logout.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        Logout.setForeground(java.awt.Color.white);
        Logout.setLabel("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        add(Logout);
        Logout.setBounds(10, 50, 70, 20);

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setBackground(java.awt.Color.red);
        label2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        label2.setForeground(java.awt.Color.white);
        label2.setText("BATCH MASTER LIST"); // NOI18N
        add(label2);
        label2.setBounds(10, 80, 350, 25);

        label3.setAlignment(java.awt.Label.CENTER);
        label3.setBackground(java.awt.Color.red);
        label3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        label3.setForeground(java.awt.Color.white);
        label3.setText("LIST ITEMS INDEX"); // NOI18N
        add(label3);
        label3.setBounds(10, 590, 350, 20);

        label4.setAlignment(java.awt.Label.CENTER);
        label4.setBackground(java.awt.Color.red);
        label4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        label4.setForeground(java.awt.Color.white);
        label4.setText("1) BATCH ID"); // NOI18N
        add(label4);
        label4.setBounds(10, 610, 350, 20);

        label5.setAlignment(java.awt.Label.CENTER);
        label5.setBackground(java.awt.Color.red);
        label5.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        label5.setForeground(java.awt.Color.white);
        label5.setText("2) BATCH NAME"); // NOI18N
        add(label5);
        label5.setBounds(10, 630, 350, 20);

        label6.setAlignment(java.awt.Label.CENTER);
        label6.setBackground(java.awt.Color.red);
        label6.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        label6.setForeground(java.awt.Color.white);
        label6.setText("3) COURSE NAME"); // NOI18N
        add(label6);
        label6.setBounds(10, 650, 350, 20);

        label7.setAlignment(java.awt.Label.CENTER);
        label7.setBackground(java.awt.Color.red);
        label7.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        label7.setForeground(java.awt.Color.white);
        label7.setText("4) FACULTY NAME"); // NOI18N
        add(label7);
        label7.setBounds(10, 670, 350, 20);

        label8.setAlignment(java.awt.Label.CENTER);
        label8.setBackground(java.awt.Color.red);
        label8.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        label8.setForeground(java.awt.Color.white);
        label8.setText("7) END TIME"); // NOI18N
        add(label8);
        label8.setBounds(10, 730, 350, 20);

        label9.setAlignment(java.awt.Label.CENTER);
        label9.setBackground(java.awt.Color.red);
        label9.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        label9.setForeground(java.awt.Color.white);
        label9.setText("5) START TIME"); // NOI18N
        add(label9);
        label9.setBounds(10, 690, 350, 20);

        label10.setAlignment(java.awt.Label.CENTER);
        label10.setBackground(java.awt.Color.red);
        label10.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        label10.setForeground(java.awt.Color.white);
        label10.setText("8) MERIDIAN (AM/PM)"); // NOI18N
        add(label10);
        label10.setBounds(10, 750, 350, 20);

        menuBar1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N

        menu1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        menu1.setLabel("Add"); // NOI18N

        menuItem3.setLabel("New Student"); // NOI18N
        menuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem3ActionPerformed(evt);
            }
        });
        menu1.add(menuItem3);

        menuItem4.setLabel("New Batch"); // NOI18N
        menuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem4ActionPerformed(evt);
            }
        });
        menu1.add(menuItem4);

        menuBar1.add(menu1);

        menu2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        menu2.setLabel("Search"); // NOI18N

        menuItem1.setLabel("Course"); // NOI18N
        menuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem1ActionPerformed(evt);
            }
        });
        menu2.add(menuItem1);

        menuItem2.setLabel("Student"); // NOI18N
        menuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem2ActionPerformed(evt);
            }
        });
        menu2.add(menuItem2);

        menuBar1.add(menu2);

        menu4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        menu4.setLabel("Change"); // NOI18N

        menuItem7.setLabel("Student's timing"); // NOI18N
        menuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem7ActionPerformed(evt);
            }
        });
        menu4.add(menuItem7);

        menuItem8.setLabel("Batch timings"); // NOI18N
        menuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem8ActionPerformed(evt);
            }
        });
        menu4.add(menuItem8);

        menuItem9.setLabel("TOPIC"); // NOI18N
        menuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem9ActionPerformed(evt);
            }
        });
        menu4.add(menuItem9);

        menuBar1.add(menu4);

        menu5.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        menu5.setLabel("Create"); // NOI18N

        menuItem5.setLabel("User"); // NOI18N
        menuItem5.setName("Staff"); // NOI18N
        menuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem5ActionPerformed(evt);
            }
        });
        menu5.add(menuItem5);

        menuBar1.add(menu5);

        menu3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        menu3.setLabel("End");

        menuItem6.setLabel("Batch");
        menuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem6ActionPerformed(evt);
            }
        });
        menu3.add(menuItem6);

        menuBar1.add(menu3);

        setMenuBar(menuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void menuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem3ActionPerformed
        // TODO add your handling code here:
        NewS obj=new NewS();
        obj.setVisible(true);
        obj.setBounds(370,80,900,650);
    }//GEN-LAST:event_menuItem3ActionPerformed

    private void menuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem4ActionPerformed
        // TODO add your handling code here:
        NewBatch n=new NewBatch();
        n.setVisible(true);
        n.setBounds(363,48,900,750);
    }//GEN-LAST:event_menuItem4ActionPerformed

    private void menuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem1ActionPerformed
        // TODO add your handling code here:
        Searchc sc=new Searchc();
        sc.setVisible(true);
        sc.setBounds(370,80,900,650);
    }//GEN-LAST:event_menuItem1ActionPerformed

    private void menuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem2ActionPerformed
        // TODO add your handling code here:
        Search s=new Search();
        s.setVisible(true);
        s.setBounds(370,80,900,650);
    }//GEN-LAST:event_menuItem2ActionPerformed

    private void menuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem7ActionPerformed
        // TODO add your handling code here:
        ChangeTime ct=new ChangeTime();
        ct.setVisible(true);
        ct.setBounds(370,50,900,750);
    }//GEN-LAST:event_menuItem7ActionPerformed

    private void menuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem8ActionPerformed
        // TODO add your handling code here:
        ChangeBatch cb=new ChangeBatch();
        cb.setVisible(true);
        cb.setBounds(370,80,900,650);
    }//GEN-LAST:event_menuItem8ActionPerformed

    private void menuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem5ActionPerformed
        // TODO add your handling code here:
        createUser cu=new createUser();
        cu.setVisible(true);
        cu.setBounds(370,80,900,650);
    }//GEN-LAST:event_menuItem5ActionPerformed

    private void menuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem9ActionPerformed
        // TODO add your handling code here:
        changeTopic ct=new changeTopic();
         ct.setVisible(true);
        ct.setBounds(370,80,900,650);
    }//GEN-LAST:event_menuItem9ActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
       this.dispose();
        Login l=new Login();
        l.setVisible(true);
        l.setBounds(400, 200, 620, 300);
         
    }//GEN-LAST:event_LogoutActionPerformed

    private void blistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blistActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_blistActionPerformed

    private void menuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem6ActionPerformed
        // TODO add your handling code here:
        BatchEnd be=new BatchEnd();
        be.setVisible(true);

        be.setBounds(370,60,900,700);
    }//GEN-LAST:event_menuItem6ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame1(utype).setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button Logout;
    private java.awt.List blist;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.Menu menu3;
    private java.awt.Menu menu4;
    private java.awt.Menu menu5;
    private java.awt.MenuBar menuBar1;
    private java.awt.MenuItem menuItem1;
    private java.awt.MenuItem menuItem2;
    private java.awt.MenuItem menuItem3;
    private java.awt.MenuItem menuItem4;
    private java.awt.MenuItem menuItem5;
    private java.awt.MenuItem menuItem6;
    private java.awt.MenuItem menuItem7;
    private java.awt.MenuItem menuItem8;
    private java.awt.MenuItem menuItem9;
    // End of variables declaration//GEN-END:variables

}
