    /*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package hgpi;

import hgpi.Frame1;
import hgpi.Register;

import java.sql.*;
public class Login extends java.awt.Frame {

    /** Creates new form Login */
    public Login() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        tfuname = new java.awt.TextField();
        tfpwd = new java.awt.TextField();
        exit = new java.awt.Button();
        submit = new java.awt.Button();
        label4 = new java.awt.Label();
        choice1 = new java.awt.Choice();
        lblmsg = new java.awt.Label();

        setBackground(java.awt.Color.orange);
        setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        setName(""); // NOI18N
        setTitle("enter login details"); // NOI18N
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(null);

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setBackground(java.awt.Color.red);
        label1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        label1.setForeground(java.awt.Color.white);
        label1.setText("LOGIN"); // NOI18N
        add(label1);
        label1.setBounds(0, 10, 620, 60);

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setBackground(java.awt.Color.blue);
        label2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        label2.setForeground(java.awt.Color.white);
        label2.setText("USERNAME"); // NOI18N
        add(label2);
        label2.setBounds(150, 100, 150, 30);

        label3.setAlignment(java.awt.Label.CENTER);
        label3.setBackground(java.awt.Color.blue);
        label3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        label3.setForeground(java.awt.Color.white);
        label3.setText("TYPE"); // NOI18N
        add(label3);
        label3.setBounds(150, 200, 150, 30);

        tfuname.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        tfuname.setForeground(java.awt.Color.red);
        tfuname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfunameActionPerformed(evt);
            }
        });
        add(tfuname);
        tfuname.setBounds(340, 100, 120, 25);

        tfpwd.setEchoChar('@');
        tfpwd.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        tfpwd.setForeground(java.awt.Color.red);
        tfpwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfpwdActionPerformed(evt);
            }
        });
        add(tfpwd);
        tfpwd.setBounds(340, 150, 120, 25);

        exit.setBackground(java.awt.Color.red);
        exit.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        exit.setForeground(java.awt.Color.blue);
        exit.setLabel("Exit"); // NOI18N
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        add(exit);
        exit.setBounds(340, 240, 110, 30);

        submit.setBackground(java.awt.Color.red);
        submit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        submit.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        submit.setForeground(java.awt.Color.blue);
        submit.setLabel("Submit"); // NOI18N
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        add(submit);
        submit.setBounds(190, 240, 110, 30);

        label4.setAlignment(java.awt.Label.CENTER);
        label4.setBackground(java.awt.Color.blue);
        label4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        label4.setForeground(java.awt.Color.white);
        label4.setText("PASSWORD"); // NOI18N
        add(label4);
        label4.setBounds(150, 150, 150, 30);

        choice1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        choice1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        choice1.setForeground(java.awt.Color.red);
        choice1.add("admin");
        choice1.add("staff");
        add(choice1);
        choice1.setBounds(340, 200, 120, 30);

        lblmsg.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblmsg.setForeground(java.awt.Color.white);
        lblmsg.setText("Invalid user"); // NOI18N
        lblmsg.setVisible(false);
        add(lblmsg);
        lblmsg.setBounds(20, 240, 140, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        
     


        try
       {
           Class.forName("com.mysql.jdbc.Driver");
       }
       catch(Exception e)
       {
           e.printStackTrace();
       }
       try
       {
        Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/hgpi_batches?zeroDateTimeBehavior=convertToNull","root","");
        PreparedStatement p=c.prepareStatement("select count(*) from users where uname=? and upwd=? and utype=?");
        p.setString(1,tfuname.getText() );
        p.setString(2, tfpwd.getText());
        p.setString(3, choice1.getSelectedItem());
        ResultSet r=p.executeQuery();
        r.next();
        int cnt=r.getInt(1);
        if(cnt==1)
        {
           Frame1 f=new Frame1(choice1.getSelectedItem());
           f.setVisible(true);
           f.setBounds(0,0,1280,800);
           this.dispose();
        }
        else
        {
            lblmsg.setVisible(true);
        }
       }
       catch(Exception e)
       {
           e.printStackTrace();
       }

     
    }//GEN-LAST:event_submitActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        
        this.dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void tfunameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfunameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfunameActionPerformed

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowLostFocus

    private void tfpwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfpwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfpwdActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               Login g= new Login();g.setVisible(true);
               g.setBounds(400, 200, 620, 300);

            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Choice choice1;
    private java.awt.Button exit;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label lblmsg;
    private java.awt.Button submit;
    private java.awt.TextField tfpwd;
    private java.awt.TextField tfuname;
    // End of variables declaration//GEN-END:variables

}
