

package hgpi;
import java.sql.*;

public class Register extends java.awt.Frame {

    /** Creates new form Register */
    static int bid;
    static String crsnm;

    public Register(int b,String c) {
        initComponents();
        bid=b;
        crsnm=c;
        int i=0,x;
        String m;
        txfb.setText(Integer.toString(bid));
        try{
            Class.forName("com.mysql.jdbc.Driver");
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        try{
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hgpi_batches?zeroDateTimeBehavior=convertToNull","root","");
            PreparedStatement p=con.prepareStatement("select sid from students");
            ResultSet rs=p.executeQuery();
            do
            {
                i++;
            }
            while(rs.next());
            txfid.setText(Integer.toString(i));
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        try{
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hgpi_batches?zeroDateTimeBehavior=convertToNull","root","");
            PreparedStatement p=con.prepareStatement("select crsid,crsname from courses");
            ResultSet rs=p.executeQuery();
            while(rs.next())
            {
                x=rs.getInt(1);
               m=rs.getString(2);

               if(crsnm.equals(m))
                {
                    
                    txfcrs.setText(Integer.toString(x));
                }
            }


        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        
    }

                   //con.prepareStatement("insert into students values(?,?,?,?,?,?,?);
                   //rs.setInt(1,getText());
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        label7 = new java.awt.Label();
        txfnm = new java.awt.TextField();
        label10 = new java.awt.Label();
        txfid = new java.awt.TextField();
        label13 = new java.awt.Label();
        txfphn = new java.awt.TextField();
        txfe = new java.awt.TextField();
        label15 = new java.awt.Label();
        register = new java.awt.Button();
        label12 = new java.awt.Label();
        txfdoj = new java.awt.TextField();
        label14 = new java.awt.Label();
        txfb = new java.awt.TextField();
        lbdat = new java.awt.Label();
        txfcrs = new java.awt.TextField();
        label17 = new java.awt.Label();
        fmissing = new java.awt.Label();
        lbem = new java.awt.Label();

        setBackground(java.awt.Color.orange);
        setUndecorated(true);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(null);

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setBackground(java.awt.Color.red);
        label1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        label1.setForeground(java.awt.Color.white);
        label1.setText("REGISTER NEW STUDENT"); // NOI18N
        add(label1);
        label1.setBounds(0, 40, 740, 60);

        label7.setAlignment(java.awt.Label.CENTER);
        label7.setBackground(java.awt.Color.blue);
        label7.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        label7.setForeground(java.awt.Color.white);
        label7.setText("STUDENT NAME"); // NOI18N
        add(label7);
        label7.setBounds(510, 130, 170, 25);

        txfnm.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        txfnm.setForeground(java.awt.Color.red);
        add(txfnm);
        txfnm.setBounds(700, 130, 170, 25);

        label10.setAlignment(java.awt.Label.CENTER);
        label10.setBackground(java.awt.Color.blue);
        label10.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        label10.setForeground(java.awt.Color.white);
        label10.setText("PHONE NUMBER"); // NOI18N
        add(label10);
        label10.setBounds(80, 270, 170, 25);

        txfid.setEditable(false);
        txfid.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        txfid.setForeground(java.awt.Color.red);
        add(txfid);
        txfid.setBounds(280, 130, 160, 25);

        label13.setAlignment(java.awt.Label.CENTER);
        label13.setBackground(java.awt.Color.blue);
        label13.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        label13.setForeground(java.awt.Color.white);
        label13.setText("EMAIL ID"); // NOI18N
        add(label13);
        label13.setBounds(510, 270, 170, 25);

        txfphn.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        txfphn.setForeground(java.awt.Color.red);
        add(txfphn);
        txfphn.setBounds(280, 270, 160, 25);

        txfe.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        txfe.setForeground(java.awt.Color.red);
        add(txfe);
        txfe.setBounds(700, 270, 170, 25);

        label15.setAlignment(java.awt.Label.CENTER);
        label15.setBackground(java.awt.Color.blue);
        label15.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        label15.setForeground(java.awt.Color.white);
        label15.setText("STUDENT ID"); // NOI18N
        add(label15);
        label15.setBounds(80, 130, 170, 25);

        register.setBackground(java.awt.Color.red);
        register.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        register.setForeground(java.awt.Color.blue);
        register.setLabel("REGISTER"); // NOI18N
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        add(register);
        register.setBounds(430, 630, 120, 29);

        label12.setAlignment(java.awt.Label.CENTER);
        label12.setBackground(java.awt.Color.blue);
        label12.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        label12.setForeground(java.awt.Color.white);
        label12.setText("DATE OF JOINING"); // NOI18N
        add(label12);
        label12.setBounds(80, 400, 170, 25);

        txfdoj.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        txfdoj.setForeground(java.awt.Color.red);
        txfdoj.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txfdojFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txfdojFocusLost(evt);
            }
        });
        add(txfdoj);
        txfdoj.setBounds(280, 400, 160, 25);

        label14.setAlignment(java.awt.Label.CENTER);
        label14.setBackground(java.awt.Color.blue);
        label14.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        label14.setForeground(java.awt.Color.white);
        label14.setText("BATCH ID"); // NOI18N
        add(label14);
        label14.setBounds(510, 400, 170, 25);

        txfb.setEditable(false);
        txfb.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        txfb.setForeground(java.awt.Color.red);
        add(txfb);
        txfb.setBounds(700, 400, 50, 25);

        lbdat.setAlignment(java.awt.Label.CENTER);
        lbdat.setBackground(java.awt.Color.blue);
        lbdat.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lbdat.setForeground(java.awt.Color.white);
        lbdat.setText("* mm-dd-yyyy"); // NOI18N
        lbdat.setVisible(false);
        add(lbdat);
        lbdat.setBounds(280, 430, 110, 25);

        txfcrs.setEditable(false);
        txfcrs.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        txfcrs.setForeground(java.awt.Color.red);
        add(txfcrs);
        txfcrs.setBounds(510, 520, 160, 25);

        label17.setAlignment(java.awt.Label.CENTER);
        label17.setBackground(java.awt.Color.blue);
        label17.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        label17.setForeground(java.awt.Color.white);
        label17.setText("COURSE ID"); // NOI18N
        add(label17);
        label17.setBounds(300, 520, 170, 25);

        fmissing.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        fmissing.setForeground(java.awt.Color.white);
        fmissing.setText("Some fields are missing, please fill them!");
        fmissing.setVisible(false);
        add(fmissing);
        fmissing.setBounds(600, 630, 300, 25);

        lbem.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lbem.setForeground(java.awt.Color.white);
        lbem.setText("ENTER A VALID EMAIL ID");
        lbem.setVisible(false);
        add(lbem);
        lbem.setBounds(700, 310, 200, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
       // System.exit(0);
       this.dispose();
    }//GEN-LAST:event_exitForm

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        // TODO add your handling code here:
         
            

      if((txfnm.getText()).equals("") || (txfphn.getText()).equals("") || (txfdoj.getText()).equals("") || (txfe.getText()).equals(""))
        {
            fmissing.setVisible(true);
        }
     
        

        else{
        lbem.setVisible(false);
        fmissing.setVisible(false);
        try{
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hgpi_batches?zeroDateTimeBehavior=convertToNull","root","");
            PreparedStatement p=con.prepareStatement("insert into students values(?,?,?,?,?,?,?)");
            p.setInt(1,Integer.parseInt(txfid.getText()));
            p.setString(2,txfnm.getText());
               System.out.println(txfnm.getText());

            p.setInt(3,Integer.parseInt(txfcrs.getText()));
            p.setString(4,txfdoj.getText());
            p.setString(5,txfphn.getText());
            p.setString(6,txfe.getText());
            p.setInt(7,Integer.parseInt(txfb.getText()));
            p.executeUpdate();
            }
        catch(Exception e)
        {
            e.printStackTrace();
        }
          try{
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hgpi_batches?zeroDateTimeBehavior=convertToNull","root","");
            PreparedStatement p=con.prepareStatement(" update batches set totstu=totstu+1 where bid=?");

            p.setInt(1,bid);
            p.executeUpdate();
            }
        catch(Exception e)
        {
            e.printStackTrace();
        }
         newBatchnext nbn=new newBatchnext(bid,crsnm);
        nbn.setVisible(true);
        nbn.setBounds(400, 200, 620, 300);
        }
    }//GEN-LAST:event_registerActionPerformed

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_formWindowLostFocus

    private void txfdojFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfdojFocusLost
        // TODO add your handling code here:
        lbdat.setVisible(false);
    }//GEN-LAST:event_txfdojFocusLost

    private void txfdojFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfdojFocusGained
        // TODO add your handling code here:
        lbdat.setVisible(true);
    }//GEN-LAST:event_txfdojFocusGained

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register(bid,crsnm).setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label fmissing;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label12;
    private java.awt.Label label13;
    private java.awt.Label label14;
    private java.awt.Label label15;
    private java.awt.Label label17;
    private java.awt.Label label7;
    private java.awt.Label lbdat;
    private java.awt.Label lbem;
    private java.awt.Button register;
    private java.awt.TextField txfb;
    private java.awt.TextField txfcrs;
    private java.awt.TextField txfdoj;
    private java.awt.TextField txfe;
    private java.awt.TextField txfid;
    private java.awt.TextField txfnm;
    private java.awt.TextField txfphn;
    // End of variables declaration//GEN-END:variables

}
