
package hgpi;
import java.sql.*;
/**
 *
 * @author CIET
 */
public class Searchc extends java.awt.Frame {

    /** Creates new form Searchc */
    public Searchc() {
        initComponents();
        try{
           Class.forName("com.mysql.jdbc.Driver");   
        }
        catch(Exception e)
        {
           e.printStackTrace();
        }
       try{
          Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/hgpi_batches?zeroDateTimeBehavior=convertToNull","root","");
            PreparedStatement p=c.prepareStatement("select crsname from courses");
            ResultSet rs=p.executeQuery();
            while(rs.next())
            {
                chcrs.add(rs.getString(1));
            }
         }
         catch(Exception e)
         {
             e.printStackTrace();
         }
          
         
       

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        chcrs = new java.awt.Choice();
        label4 = new java.awt.Label();
        button1 = new java.awt.Button();

        setBackground(java.awt.Color.orange);
        setUndecorated(true);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(null);

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setBackground(java.awt.Color.red);
        label1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        label1.setForeground(java.awt.Color.white);
        label1.setText("SEARCH COURSE");
        add(label1);
        label1.setBounds(0, 40, 600, 60);

        chcrs.setBackground(java.awt.Color.white);
        chcrs.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        chcrs.setForeground(java.awt.Color.red);
        chcrs.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                chcrsInputMethodTextChanged(evt);
            }
        });
        add(chcrs);
        chcrs.setBounds(390, 250, 150, 25);

        label4.setAlignment(java.awt.Label.CENTER);
        label4.setBackground(java.awt.Color.blue);
        label4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        label4.setForeground(java.awt.Color.white);
        label4.setText("COURSE");
        add(label4);
        label4.setBounds(70, 250, 170, 20);

        button1.setBackground(java.awt.Color.red);
        button1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        button1.setForeground(java.awt.Color.blue);
        button1.setLabel("SEARCH");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        add(button1);
        button1.setBounds(240, 390, 100, 29);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
         
        SearchResultc s=new SearchResultc(chcrs.getSelectedItem());
        s.setVisible(true);
        s.setBounds(370,80,900,650);
    }//GEN-LAST:event_button1ActionPerformed

    private void chcrsInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_chcrsInputMethodTextChanged
        // TODO add your handling code here:
        try{
            Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/hgpi_batches?zeroDateTimeBehavior=convertToNull","root","");
         PreparedStatement ps=c.prepareStatement("select crsid from courses where crsname=?");
            ps.setString(1,chcrs.getSelectedItem());
            ResultSet r=ps.executeQuery();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_chcrsInputMethodTextChanged

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_formWindowLostFocus

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Searchc().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Choice chcrs;
    private java.awt.Label label1;
    private java.awt.Label label4;
    // End of variables declaration//GEN-END:variables

}
